[package]
name = "cmd-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }

[features]
dx-test = ["tokio"]

[dev-dependencies]
tempfile = "3"
